### ISSUE TITLE
Assignment 4 question

### ISSUE THREAD

**Issue by bmnguyen6403** [LeDataSciFi/ledatascifi-2024#17]
In assignment 4 part 2, there is a line:
"Reduce the data to gsectors 15, 35, 20, 45, 40, 25, and years 1980-2010."
Is it to reduce the ccm data or to use the patent-level RETech data in part 3?

**Comment by donbowen** [comment]
@bmnguyen6403  I’m sorry I never replied to this issue. It’s because you didn’t tag me (by adding “ @donbowen”) so I didn’t get a notification.
