### ISSUE TITLE
Assignment 4 Grading Clarification Question

### ISSUE THREAD

**Issue by michaelparker7** [LeDataSciFi/ledatascifi-2024#20]
@donbowen For the question "Part 1: Did they include "how", "on", "indicator=True", and validate="1:M" (or "one_to_many") in EVERY merge for Part 1?" I believe the answer key validates a 1:1 for every merge, just want to know how we are meant to answer this one.

Also, for the question "Part 2: Q9 reports the average RETech *for year 2000* in gsector 20 (industrials) as 0.963 AND gsector 45 is 2.161." I believe your answer key says the correct answers are 0.963 and 1.796, not 0.963 and 2.161. Just wanted clarification on if this was intentional or not.

**Comment by donbowen** [comment]
Both good catches. Thanks!

I updated the form. Luckily, only a few reviews have been submitted.
